name: Test

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npm run coverage
      - name: Install CodeScene coverage CLI
        run: curl https://downloads.codescene.io/enterprise/cli/install-cs-coverage-tool.sh | bash -s -- -y
      - name: Upload coverage to CodeScene
        run: cs-coverage upload --format "lcov" --metric "line-coverage" "coverage/lcov.info"
        env:
          CS_ACCESS_TOKEN: ${{ secrets.CS_ACCESS_TOKEN }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: coverage/lcov.info

  cs-coverage-check:
    runs-on: ubuntu-latest
    needs: [test]
    if: always()
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          path: coverage/
      - uses: ./.github/actions/check-coverage
        if: always()
        with:
          access-token: ${{ secrets.CODESCENE_API_TOKEN }}
          project-url: "https://api.codescene.io/v2/projects/81232"
          coverage-files: "**/coverage/lcov.info"
